### PR TITLE
Support Spree v3.0 and make admin tables responsive.

### PR DESCRIPTION
**Pull request by vmatekole**
Hi,

I am a newbie to Spree and am using v3.0 for a new project and wanted to use spree_slider... 
I may have made some obvious mistakes and/or have missed some changes to fully support the prerequisites of Spree v3.0. Nonetheless, these changes work for me thus far. Please review and let me know your feedback.

### CODE REVIEW

**Comment by priviterag** [comment]
@vmatekole Thanks a lot, mate!

@JDutil Please, could you review/merge it?

**Comment by JDutil** [comment]
@priviterag it looks fine to get things working to me, but there are other things that could be done for 3.0 improvements on top of it after.

The question now though is that this extension has been loosely versioned because it doesn't need to be strict.  We need to bump the spree_core requirement with these changes though.  So what do we want to name the 2.2-2.4 compatible branch? Or do we just create a 2-2-stable, 2-3-stable, 2-4-stable branch for each even though they are all the same.

**Comment by jspizziri** [comment]
@vmatekole, `master` has recently been updated to support spree 3.0 with this PR: https://github.com/spree-contrib/spree_slider/pull/6 . 

I did it without realizing this PR existed. With that said, I did not make the tables responsive, so if you would like to submit a new PR please do.

**Comment by berkes** [comment]
I'd vote for a consistent branch-naming even if that is superfluous. So I'd say it is best to create `2-2-stable`, 2-3-stable`, `2-4-stable` which may all be at the same commit even. And then a `3-0-stable` which is forked off the latest master.

IMO this has two benefits:
* I can easily see whether a plugin was made compatible with a version by seeing if the branch is there. In general, when I don't see a 3-0-stable branch, I assume it is not considered ready or stable for that version. Only when I really need a plugin, I might search through the opened and closed PRs and issues to see wether it has been ported. The Versionfile might be used as such too, but is far less visible and cannot be used in the Gemfile of your Spree site: branches can.
* It allows older releases to remain stable: New features can then only be applied to specific branches, so that users can choose to not get these new features (that might break their implementation or usage).

Just my $0.02

**Comment by JDutil** [comment]
I've created 3-0-stable branch based off latest commit, and create 2-2-stable 2-3-stable and 2-4-stable branches based off the previous commit before 3.0.0 support.  would be good to update this pr with master

**Comment by berkes** [comment]
AFAIK this PR is superflous, since most fixes are already done in #6. Is there anything in this PR that should go into the 3.0 branch, @vmatekole? If you can point that out, I'll fix that.

**Comment by jspizziri** [comment]
@berkes, that is correct. The only think that wasn't in #6 was any work legitimate work on responsive tables.

@vmatekole if you wanted to submit a PR with that work in it I would encourage it. Otherwise I think this PR should be closed.

**Comment by vmatekole** [comment]
hi, for some reason I didn't get notifications for these comments. I am fine with conclusions here... If I see anything missing in 3-0-stable branch I will create a PR. Danke.

**Pull request closed without merging**
